version: "2.4"
# need to change traefit ip and buffer reader.py

services:
  status_register:
    image: memcached
    container_name: status_register
    # restart: always
    command: memcached -m 2 -p 12001

  image_register_A:
    image: memcached
    container_name: image_register_A
    # restart: always
    command: memcached -m 64 -p 12002 -I 4m

  image_register_B:
    image: memcached
    container_name: image_register_B
    # restart: always
    command: memcached -m 64 -p 12003 -I 4m

  fod_image_register_A:
    image: memcached
    container_name: fod_image_register_A
    # restart: always
    command: memcached -m 64 -p 12004 -I 4m

  fod_image_register_B:
    image: memcached
    container_name: fod_image_register_B
    # restart: always
    command: memcached -m 64 -p 12005 -I 4m

  db:
    image: postgres
    container_name: postgres
    # restart: always
    volumes:
      - yq_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=quantum
      - POSTGRES_DB=yqdb
      - POSTGRES_PASSWORD=429526000

  web:
    image: registry.cn-hangzhou.aliyuncs.com/yqfods/web:latest
    container_name: web
    # restart: always
    environment: 
      - VUE_APP_SERVER_URL=192.168.43.69:8081
    # volumes:
    #   - ./web/web:/web
    #   - ./fod_model/photos:/web/dist/img/photos
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`192.168.43.69`)"
      - "traefik.http.routers.web.entrypoints=web"
      - "traefik.http.services.web.loadBalancer.server.port=80"

  server:
    image: registry.cn-hangzhou.aliyuncs.com/yqfods/server:2.2.0
    container_name: server
    # restart: always
    environment: 
      - DATABASE_URL=postgresql://quantum:429526000@postgres/yqdb
      - HLS_SERVER_URL=192.168.43.69
    depends_on:
      - db
    volumes:
      - ./server:/server
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.server.rule=Host(`192.168.43.69`)"
      - "traefik.http.routers.server.entrypoints=server"
      - "traefik.http.services.server.loadBalancer.server.port=8000"
    command: gunicorn -k gevent -w 5 -b server:8000 wsgi:app
    # command: flask init

  traefik:
    image: traefik
    container_name: traefik
    # restart: always
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    ports: 
      - "10101:80"
      - "8081:8081"
    depends_on:
      - web
      - server
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.server.address=:8081"

  nginx:
    image: registry.cn-hangzhou.aliyuncs.com/yqfods/nginx:latest
    container_name: nginx
    # restart: always
    ports:
      - "8082:8082"

  buffer:
    image: registry.cn-hangzhou.aliyuncs.com/yqfods/buffer:2.2.0
    container_name: buffer
    # restart: always
    environment: 
      - WORK_ENV=development
    volumes:
      - ./buffer:/code
    depends_on: 
      - nginx
    command: python video_buffer.py

  fod_model:
    image: registry.cn-hangzhou.aliyuncs.com/yqfods/fod_model:latest
    container_name: fod_model
    # restart: always
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=6,7
    depends_on:
      - fod_image_register_A
      - fod_image_register_B
    volumes:
      - ./fod_model/yolov5:/yolov5
      # - ./fod_model/photos:/yolov5/photos
    command: python detect.py

volumes:
  yq_data:
    external: true

networks: 
  default:
    name: yuhao_network
