version: "2.4"

services:
  status_register:
    container_name: status_register
    image: memcached
    command: memcached -m 2 -p 12001

  image_register_A:
    container_name: image_register_A
    image: memcached
    command: memcached -m 64 -p 12002 -I 4m

  image_register_B:
    container_name: image_register_B
    image: memcached
    command: memcached -m 64 -p 12003 -I 4m

  db:
    image: postgres
    container_name: postgres
    volumes:
      - yq_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=quantum
      - POSTGRES_DB=yqdb
      - POSTGRES_PASSWORD=429526000

  web:
    image: registry.cn-hangzhou.aliyuncs.com/yqfods/web:2.0.0
    container_name: web
    command: npm run serve -- --port 8000

  server:
    container_name: server
    image: registry.cn-hangzhou.aliyuncs.com/yqfods/server:2.0.0
    environment: 
      - DATABASE_URL=postgresql://quantum:429526000@postgres/yqdb
    depends_on:
      - db
    command: gunicorn -k gevent -w 5 -b server:8000 wsgi:app
    # command: flask init

  nginx:
    image: registry.cn-hangzhou.aliyuncs.com/yqfods/nginx:2.0.0
    container_name: nginx
    ports:
      - "8082:8082"

  traefik:
    image: registry.cn-hangzhou.aliyuncs.com/yqfods/traefik:2.0.0
    container_name: traefik
    ports: 
      - "80:80"
      - "8081:8081"
    depends_on:
      - web
      - server

  fod_model:
    container_name: fod_model
    image: registry.cn-hangzhou.aliyuncs.com/yqfods/fod_model:2.0.0
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=6,7
    depends_on:
      - image_register_A
      - image_register_B
      - db
      - nginx
    volumes:
      - ./fod_model/photos:/yolo/photos
    command: python yolo.py

volumes:
  yq_data:
    external: true

networks: 
  default:
    name: yuhao_network
