version: "2.4"

services:
  status_register:
    container_name: status_register
    image: memcached
    command: memcached -m 16 -p 12001

  image_register_A:
    container_name: image_register_A
    image: memcached
    command: memcached -m 64 -p 12002 -I 4m

  image_register_B:
    container_name: image_register_B
    image: memcached
    command: memcached -m 64 -p 12003 -I 4m

  web:
    image: registry.cn-hangzhou.aliyuncs.com/yqfods/web:2.0.0
    container_name: web

  db:
    image: postgres
    container_name: postgres
    volumes:
      - yd_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=quantum
      - POSTGRES_DB=yqdb
      - POSTGRES_PASSWORD=429526000

  server:
    container_name: server
    image: registry.cn-hangzhou.aliyuncs.com/yqfods/server:2.0.0
    depends_on:
      - db
      - status_register
    command: gunicorn -k gevent -w 5 -b server:8000 server:app

  nginx:
    image: registry.cn-hangzhou.aliyuncs.com/yqfods/nginx:2.0.0
    container_name: nginx
    ports:
      - "10101:80"
      - "8081:8081"
      - "8082:8082"
    depends_on:
      - server
      - web

  fod_model:
    container_name: yolo
    image: registry.cn-hangzhou.aliyuncs.com/yqfods/fod_model:2.0.0
    runtime: nvidia
    depends_on:
      - status_register
      - image_register_A
      - image_register_B
      - db
      - nginx
    command: python yolo.py

volumes:
  yd_data:
    external: true
